# Generated by Django 3.0.5 on 2020-04-06 04:24

import apps.stays.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=apps.stays.models.upload_image_path)),
                ('second_image', models.ImageField(blank=True, null=True, upload_to=apps.stays.models.upload_image_path)),
                ('third_image', models.ImageField(blank=True, null=True, upload_to=apps.stays.models.upload_image_path)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
