# Generated by Django 3.0.5 on 2020-05-01 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
        ('amenities', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('guests', models.IntegerField(default=1)),
                ('bedroom', models.IntegerField(default=1)),
                ('beds', models.IntegerField(default=1)),
                ('baths', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('home_types', models.CharField(choices=[('Entire place', 'Entire place'), ('Private room', 'Private room'), ('Shared room', 'Shared room')], default='Entire place', max_length=30)),
                ('check_in', models.CharField(choices=[('Lockbox', 'Lockbox'), ('Keypad', 'Keypad'), ('Smartlock', 'Smartlock')], default='Lockbox', max_length=30)),
                ('description', models.CharField(max_length=1250)),
                ('featured', models.BooleanField(default=False)),
                ('main_image', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(to='amenities.Amenity')),
                ('bookings', models.ManyToManyField(blank=True, to='bookings.Booking')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviews', models.ManyToManyField(blank=True, to='reviews.Review')),
            ],
        ),
    ]
