# Generated by Django 3.0.5 on 2020-04-09 21:28

import apps.stays.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('amenities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('guests', models.IntegerField(default=1)),
                ('bedroom', models.IntegerField(default=1)),
                ('beds', models.IntegerField(default=1)),
                ('baths', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('plus', models.BooleanField(default=False)),
                ('entire_home', models.BooleanField(default=False)),
                ('check_in', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1250)),
                ('featured', models.BooleanField(default=False)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=apps.stays.models.upload_image_path)),
                ('second_image', models.ImageField(blank=True, null=True, upload_to=apps.stays.models.upload_image_path)),
                ('third_image', models.ImageField(blank=True, null=True, upload_to=apps.stays.models.upload_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(to='amenities.Amenity')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviews', models.ManyToManyField(to='reviews.Review')),
            ],
        ),
    ]
