# Generated by Django 3.0.5 on 2020-04-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='entire_home',
        ),
        migrations.AddField(
            model_name='stay',
            name='home_types',
            field=models.CharField(choices=[('entire_place', 'Entire place'), ('private_room', 'Private room'), ('shared_room', 'Shared room')], default='entire_place', max_length=30),
        ),
    ]
