# Generated by Django 3.0.5 on 2020-04-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
