# Generated by Django 3.0.5 on 2020-05-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='check_in',
            field=models.CharField(choices=[('Smartlock', 'Smartlock'), ('Lockbox', 'Lockbox'), ('Keypad', 'Keypad')], default='Lockbox', max_length=30),
        ),
    ]
