# Generated by Django 3.0.5 on 2020-04-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_stay'),
        ('stays', '0002_auto_20200409_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='bookings',
            field=models.ManyToManyField(to='bookings.Booking'),
        ),
    ]
