# Generated by Django 3.0.5 on 2020-04-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_stay'),
        ('stays', '0002_auto_20200415_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='bookings.Booking'),
        ),
    ]
