# Generated by Django 3.0.5 on 2020-04-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_auto_20200411_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='home_types',
            field=models.CharField(choices=[('Entire place', 'Entire place'), ('Private room', 'Private room'), ('Shared room', 'Shared room')], default='entire_place', max_length=30),
        ),
    ]
