# Generated by Django 3.0.5 on 2020-05-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0003_auto_20200501_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='check_in',
            field=models.CharField(choices=[('Keypad', 'Keypad'), ('Lockbox', 'Lockbox'), ('Smartlock', 'Smartlock')], default='Lockbox', max_length=30),
        ),
    ]
