# Generated by Django 3.0.5 on 2020-04-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0004_auto_20200425_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='main_image',
            field=models.CharField(max_length=100),
        ),
    ]
