# Generated by Django 3.0.5 on 2020-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0006_auto_20200430_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='check_in',
            field=models.CharField(choices=[('Smartlock', 'Smartlock'), ('Keypad', 'Keypad'), ('Lockbox', 'Lockbox')], default='Lockbox', max_length=30),
        ),
    ]
