# Generated by Django 3.0.5 on 2020-04-24 17:22

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.upload_image_path),
        ),
    ]
