# Generated by Django 3.0.5 on 2020-05-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200501_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
