# Generated by Django 3.0.5 on 2020-04-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
