# Generated by Django 3.0.5 on 2020-04-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Stays',
            new_name='Stay',
        ),
    ]
