# Generated by Django 3.0.5 on 2020-04-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stay',
        ),
    ]
