# Generated by Django 3.0.5 on 2020-04-09 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stays', '0002_auto_20200409_0528'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(help_text='End date', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(help_text='Start date', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stays.Stay'),
        ),
    ]
